# Generated by Django 4.1.7 on 2023-03-16 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuiz',
            fields=[
                ('timeCreated', models.DateTimeField(auto_now=True)),
                ('quizId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quizCode', models.CharField(max_length=10)),
                ('quiz_name', models.CharField(max_length=50)),
                ('total_Questions', models.PositiveIntegerField(default=1)),
                ('total_marks', models.PositiveIntegerField(default=1)),
                ('isTimed', models.BooleanField()),
                ('time', models.PositiveIntegerField()),
                ('isActive', models.BooleanField()),
                ('retest', models.BooleanField()),
                ('showMarks', models.BooleanField()),
                ('numberOfPeopleAttempted', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='static/images/profile_pic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('isCustom', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=25)),
                ('marks', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customQuizID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rootQuiz.customquiz')),
                ('playerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rootQuiz.player')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qID', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('question', models.CharField(max_length=600)),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('quiz_id_to_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rootQuiz.customquiz')),
            ],
        ),
        migrations.AddField(
            model_name='customquiz',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rootQuiz.player'),
        ),
    ]
