# Generated by Django 4.1.7 on 2023-03-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootQuiz', '0004_question_marks_result_iscustom_alter_player_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customquiz',
            old_name='category_name',
            new_name='quiz_name',
        ),
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
