# Generated by Django 4.1.7 on 2023-03-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rootQuiz', '0005_rename_category_name_customquiz_quiz_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='course',
            new_name='quiz_id_to_store',
        ),
    ]
