# Generated by Django 4.1.7 on 2023-03-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootQuiz', '0008_alter_customquiz_total_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option4',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=200),
        ),
    ]
