# Generated by Django 4.1.7 on 2023-03-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rootQuiz', '0012_remove_question_id_question_qid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='number',
        ),
    ]
