# Generated by Django 4.1.7 on 2023-03-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootQuiz', '0013_remove_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
